local_backend: true

backend:
  name: test-repo
#  name: git-gateway
#  branch: master

media_folder: static/img
public_folder: /img

collections:
  - name: 'articles'
    label: 'Articles'
    extension: 'mdx'
    format: 'frontmatter'
    folder: 'content/articles'
    create: true
    slug: 'index'
    media_folder: ''
    public_folder: ''
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Header Image', name: 'image', widget: 'image', allow_multiple: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
